### ISSUE TITLE
Password mismatch

### ISSUE THREAD

**Issue by AkaGambit** [Valandur/Web-API#78] opened 2018-04-10 13:36 UTC
An op made a password "Password1"
the console stated the password of the user account was "Password1"
However the password was changed to "password1"

all accounts I made personally saved properly

**Comment by Valandur** [comment] 2018-04-14 16:02
I'm afraid I need more information about this, because I can't reproduce it on my test server.
What version of Web-API and Sponge are you running? Are you sure the OP typed the password correctly?
How were you able to find out that the password was lowercase afterwards?

**Comment by AkaGambit** [comment] 2018-04-16 03:13
webapi-4.10.8-S7.1
spongeforge-1.12.2-2611-7.1.0-BETA-3006

I saw him enter the command in the console window. It was an uppercase P.
I thought it may not have saved case sensitive so I tried a lowercase p and that worked.

**Comment by Valandur** [comment] 2018-05-01 20:37
I tried reproducing this and I can't. I've also checked all code locations I can think of where a capitalization issue with passwords might arise, and didn't find anything.
If you can make this happen again and give me specific instructions then I can look into it, otherwise I'm afraid I'll have to close this issue.

**Closed** 2018-05-22 11:06 UTC
