### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.entity.monster.* cannot be cast to org.spongepowered.api.entity.EntitySnapshot

### ISSUE THREAD

**Issue by yaroslav4167** [Valandur/Web-API#97] opened 2018-06-13 00:26 UTC
Web-Api: github master-version
SpongeForge: BETA-3162
Error after killing the mob.
Log: [pastebin](http://bit.ly/2JE3qEb)

**Comment by Valandur** [comment] 2018-06-21 15:09
Hey, sorry for the late reply. I can't reproduce this error.
Can you prodive me a list of the mods on your server? You could grab it in the AdminPanel, or possibly using a Nucleus export.

**Comment by yaroslav4167** [comment] 2018-06-21 16:30
[Mods/Plugins](http://bit.ly/2MdaatD)
At me the nickname consists of Russian symbols "Ярослав". Maybe because of this?

**Comment by Valandur** [comment] 2018-06-28 20:42
Sorry for the delay on this. It was a Sponge bug and is now fixed.

Commit fixing the issue is here: https://github.com/SpongePowered/SpongeCommon/commit/80a8f74ea0123ab9be356f26c69a7e65485083d9
Use `1.12.2-7.1.0-BETA-75`+ for Vanilla and `1.12.2-2705-7.1.0-BETA-3237`+ for Forge.

**Comment by yaroslav4167** [comment] 2018-06-28 22:34
Thank you. The Issue can be closed.

**Closed** 2018-06-28 22:40 UTC
Labels: bug
