### ISSUE TITLE
commands filter

### ISSUE THREAD

**Issue by ziceptor** [Valandur/Web-API#55] opened 2017-12-02 20:12 UTC
I would like to exclude some commands from the log. Is this possible?

**Comment by Valandur** [comment] 2017-12-02 21:55
Do you mean in the server console?  
That's currently not possible, unless you use some kind of log filter plugin, but I can add that to the next version.

**Comment by ziceptor** [comment] 2017-12-02 22:09
Commands executed from the client. From the chat room.

**Comment by Valandur** [comment] 2017-12-03 12:00
Are you talking about commands like `/webapi notify` or `/webapi users add ...`?  
Why would you want to hide those?

**Comment by ziceptor** [comment] 2017-12-03 13:26
I wouldn't want in admin interface to display data input user /pass reg pass and log /pass (flexiblelogin). This can be a problem when hacking the admin.

**Comment by Valandur** [comment] 2017-12-03 18:14
Ah ok I see what the issue is. Yes I can add that, no problem. Will be in the next version!

**Closed** 2017-12-12 02:17 UTC
Labels: enhancement
